name: Behind The Mic
favicon: null
layout_spectrum: 0.3802260218653828
typography_spectrum: 0.40847
title: Behind The Mic
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#fefefe'
    - '#101415'
    - '#333834'
    - '#6c6e6d'
    - '#e3967a'
  brandStrength: 0.5625
  lightness: 0.41815152228809893
  saturation: 0.7945684145670384
  rhythmicContrast: 0.5
purpose: []
