name: Behind The Mic
favicon: null
layout_spectrum: 0.3802260218653828
typography_spectrum: 0.968403393169865
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#A690A4'
    - '#B68F9D'
    - '#C8ACAB'
    - '#FBB9BF'
    - '#E376B7'
  brandStrength: 0.6618059801403433
  lightness: 0.41815152228809893
  saturation: 0.7945684145670384
  rhythmicContrast: 0.03223387245088816
purpose: []
